Add CI for detekt

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -80,6 +80,15 @@ jobs:
             ${{ github.workspace }}/**/build/reports/lint-results*.html
             ${{ github.workspace }}/build/reports/violations.*
 
+      - name: Upload "Detekt Results".
+        if: success() || failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: Detekt Results
+          path: |
+            ${{ github.workspace }}/**/build/reports/detekt/detekt.*
+            ${{ github.workspace }}/build/reports/detekt/merge.*
+
       - name: Publish Unit Test Results
         if: success() || failure()
         uses: EnricoMi/publish-unit-test-result-action@v1
@@ -89,3 +98,25 @@ jobs:
           report_individual_runs: true
           test_changes_limit: 0
           files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml
+
+      - name: Fail if Detekt is missing report or has warnings.
+        run: |
+          if [ ! -f 'build/reports/detekt/merge.sarif' ]; then # -f: Path exists and is regular file.
+            echo "Detekt report file does not exist"
+            exit 2
+          fi
+          if [ ! -f 'build/reports/detekt/merge.xml' ]; then # -f: Path exists and is regular file.
+            echo "Detekt report file does not exist"
+            exit 3
+          fi
+          if [ `grep -c '  <file name=' merge.xml` != 0 ]; then # -c: count number of instances
+            echo "There were detekt failures."
+            exit 4
+          fi
+
+      - name: Publish Detekt Results
+        uses: github/codeql-action/upload-sarif@v1
+        if: success() || failure()
+        with:
+          checkout_path: ${{ github.workspace }}
+          sarif_file: ${{ github.workspace }}/build/reports/detekt/merge.sarif
