Code review

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -48,13 +48,22 @@ jobs:
           --no-daemon
           --no-build-cache
           --stacktrace
-          -x lint
-          -x test
+          assemble
           check
           violationReportHtml
           violationCountFile
 
+      - name: Upload "Lint Results".
+        if: success() || failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: Lint Results HTMLs
+          path: |
+            ${{ github.workspace }}/**/build/reports/lint-results*.html
+            ${{ github.workspace }}/build/reports/violations.*
+
       - name: Fail if there are violations
+        if: success() || failure()
         run: |
           count=$(cat "${{ github.workspace }}/build/reports/violations.count")
           if [[ "$count" != "0" ]]; then
@@ -72,24 +81,6 @@ jobs:
           name: Unit Test Results
           path: ${{ github.workspace }}/**/build/reports/tests/*/
 
-      - name: Upload "Lint Results".
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: Lint Results HTMLs
-          path: |
-            ${{ github.workspace }}/**/build/reports/lint-results*.html
-            ${{ github.workspace }}/build/reports/violations.*
-
-      - name: Upload "Detekt Results".
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: Detekt Results
-          path: |
-            ${{ github.workspace }}/**/build/reports/detekt/detekt.*
-            ${{ github.workspace }}/build/reports/detekt/merge.*
-
       - name: Publish Unit Test Results
         if: success() || failure()
         uses: EnricoMi/publish-unit-test-result-action@v1
@@ -100,36 +91,28 @@ jobs:
           test_changes_limit: 0
           files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml
 
+      - name: Upload "Detekt Results".
+        if: success() || failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: Detekt Results
+          path: |
+            ${{ github.workspace }}/**/build/reports/detekt/detekt.*
+            ${{ github.workspace }}/build/reports/detekt/merge.*
+
       - name: Fail if Detekt is missing merged report or has warnings.
         if: success() || failure()
         run: |
           mergedReport=build/reports/detekt/merge.xml
-
-          # Fail if Detekt failed.
-          if [ ! -f "${mergedReport}" ]; then # -f: Path exists and is regular file.
-            echo "Detekt report file '${mergedReport}' does not exist."
-            exit 3
-          fi
-          count=$(grep --count '<file name=' "${mergedReport}" || true) 
-          if [ $count != 0 ]; then 
-            echo "There were $count Detekt failures in '${mergedReport}'."
-            exit 4
-          fi
-
-          exit 0 # Be explicit, we're all good. Otherwise `grep`'s $? is returned and build fails. 
-
-      - name: Fail if Detekt is missing Sarif report for publishing on GitHub.
-        if: success() || failure()
-        run: |
-          mergedReport=build/reports/detekt/merge.sarif
-
-          # Fail if Detekt has no sarif, because we can't report to GitHub.
           if [ ! -f "${mergedReport}" ]; then # -f: Path exists and is regular file.
             echo "Detekt report file '${mergedReport}' does not exist."
             exit 2
           fi
-
-          exit 0 # Be explicit, we're all good.
+          count=$(grep --count '<file name=' "${mergedReport}" || true) 
+          if [ $count != 0 ]; then 
+            echo "There were $count Detekt failures in '${mergedReport}'."
+            exit 3
+          fi
 
       - name: Publish Detekt Results
         uses: github/codeql-action/upload-sarif@v1
@@ -137,3 +120,12 @@ jobs:
         with:
           checkout_path: ${{ github.workspace }}
           sarif_file: ${{ github.workspace }}/build/reports/detekt/merge.sarif
+
+      - name: Fail if Detekt is missing Sarif report for publishing on GitHub.
+        if: success() || failure()
+        run: |
+          mergedReport=build/reports/detekt/merge.sarif
+          if [ ! -f "${mergedReport}" ]; then # -f: Path exists and is regular file.
+            echo "Detekt report file '${mergedReport}' does not exist."
+            exit 2
+          fi
